modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="http://github.com/MineLittlePony/HDSkins/issues/"
logoFile="hdskins_logo.png"

[[mods]]
    modId="hdskins"
    version="5.0.0"
    displayName="HD Skins"
    credits="Mumfrey,Killjoy1221,Sollace"
    authors="Mumfrey"
    description='''
Faster, stronger, more res skin servers for Minecraft.

Access via the main menu.'''

[[dependencies.hdskins]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hdskins]]
    modIddd="kirin"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="CLIENT"
