name: Run Gradle on push and pull request
on:
  - push
  - pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check

